import { Component } from "@angular/core";

// function log(target, name, descriptor) { //MEMBER DECORATOR
//   console.log(target, name, descriptor);
//   const original = descriptor.value;
//   // original();
//   descriptor.value = function(...args) {
//     console.log("Argugment", args, "were passed in the funciton");
//     const result = original.apply(this, args);
//     console.log("the result of the function is ", result);
//     return result;
//   };
//   return descriptor;
// }

// function log(className) {
//   // CLASS DECORATOR
//   console.log(className);
//   return (...args) => {
//     console.log("arguments passed to thei class's contructor are ", args);
//     return new className(...args);
//   };
// }
// @log // CLASS DECORATOR
// class myExampleClass {
//   constructor(arg1, arg2) {
//     console.log("consturor fired!");
//   }
// }
// const myClass = new myExampleClass(5, 10);

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  title = "intro2angular";
  text = "app";
  // updateValue(e) {
  //   this.text = e.target.value;
  //   console.log(e.target.value);
  // }

  // constructor() {
  //   console.log(
  //     "this statement was generated by the consturtor",
  //     this.aSimpleMehtod(5, 2)
  //   );
  // }

  // // @log // MEMBER DECORATOR
  // aSimpleMehtod(a, b) {
  //   // console.log("hey there");
  //   return a * b;
  // }
}
